###########################################################
# THIS PYTHON FILE SHOULD BE IGNORED AS IT IS ONLY HERE   #
# TEMPORARILY IN ORDER TO MAKE THIS JAVA SAMPLE APPEAR TO #
# WORK IN THE PYTHON BASED cloud-playground.appspot.com   #
###########################################################

application: your-app-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.APP
